### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by pombredanne** [JDonner/SuffixTree#4]
Hi, I wonder what the license would be for this fine code?
I could not find a license here nor in https://hkn.eecs.berkeley.edu/~dyoo/python/suffix_trees/ nor in http://web.cs.ucdavis.edu/~gusfield/strmat.html (its predecessor)

**Comment by JDonner** [comment]
From Daniel Gusfield (private communication), 2017-10-31: 
"Thanks for contacting me. Strmat was written before the days of licences, and I am happy just to see it used and given new life with new implementations, or extensions. I don't know what the UC administration's view is, but my view is that as long as you cite me, and put the history of strmat in your programs, and let me know of any updated versions you produce, enjoy!"

I guess, being as it's from Berkeley, assume it's the most permissive version of the Berkeley license. Or any other one that frees Berkeley from liability. (MIT eg, or any of the other commerce-friendly ones.)

**Comment by pombredanne** [comment]
@JDonner Thanks++ for following up on this. You are a mensch!
The thing is that we just cannot assume a license (e.g. here possibly a B(erkeley)SD if none was granted explicitly and this private email does not grant one :|
