### ISSUE TITLE
installed with anaconda

### ISSUE THREAD

**Issue by cshanbo** [JDonner/SuffixTree#5]
i installed the package with anaconda python
there's no error occurred, but when i import SubstringDict, it stiil gives "no module named SubstringDict "

**Comment by mbelmadani** [comment]
What command are you running, and what do you see exactly?
I cloned the repository, and imported SubstringDict like so:
`
mkdir sandbox
cd sandbox
git clone https://github.com/JDonner/SuffixTree.git
cd SuffixTree
python setup.py install --user
cd ../../ # It's important that you python script ou interactive shell where you're trying to import SubstringDict is not where you cloned the SuffixTree repository, or else the module name SuffixTree and the directory name SuffixTree can get confused.

python
>>> import SuffixTree
>>> import SubstringDict # This doesn't work.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named SubstringDict
>>> from SuffixTree import SubstringDict # This works!
>>> 
`

Try these, and make sure the clone repository directory is not where you're running python, and also that you import SubstringDict from SuffixTree as in the last line.

**Comment by kobecsb** [comment]
Hi,
It seems the installed path was’t added to the sys.path.
I solved the problem by adding installed path to sys.path in python script.

Thank you for your reply
Shanbo Cheng
cshanbo@gmail.com

**Comment by JDonner** [comment]
> the installed path was’t added to the sys.path.

Is this something I should fix? It's been a while since I've been in this code. Is the directory structure confusing? 

Thanks mbelmadani for helping  kobecsb out.
Jeff

**Comment by kobecsb** [comment]
No. I forgot to install with: python setup.py install --user. Thank you for your help
